### ISSUE TITLE
安装时提示准备软件更新时出错

### ISSUE THREAD

**Issue by MrLiu789** [iXeor/Dell-Inspiron-7572-BigSur-OC#1]
同是7572，用您的efi尝试安装bigsur时不管是全新安装还是旧系统升级都在二次安装时提示软降更新时出错，用的是白果网卡，折腾一月了，无解。

**Comment by iXeor** [comment]
这样啊...用的白果网卡，博通的那个需要启用博通驱动然后启动项要添加一些参数。您可以使用[ @Lyn的Dell-7472-7572-Hackintosh-EFI](https://github.com/lyngogogog/Dell-7472-7572-Hackintosh-EFI/blob/master/EFI/OC/config.plist)里的plist配置文件尝试替换一下

**Comment by iXeor** [comment]
因为我自己电脑用的AX200，然后装了AirportItlwm，把博通网卡的启动参数删掉了（驱动还有保留，但是禁用了）

**Comment by MrLiu789** [comment]
> 因为我自己电脑用的AX200，然后装了AirportItlwm，把博通网卡的启动参数删掉了（驱动还有保留，但是禁用了）

谢谢，我去试一试
