### ISSUE TITLE
iMessage、FaceTime无法使用；注意换三码；耳机插孔使用需要插入补丁

### ISSUE THREAD

**Issue by Jason-ship** [iXeor/Dell-Inspiron-7572-BigSur-OC#2]
试了好多种方法，iMessage还是没办法用，估计是进黑名单了；
声卡补丁自己要打一下ALC 255/256 https://github.com/hackintosh-stuff/ComboJack

**Comment by iXeor** [comment]
ALC 255/256那个问题怨我，没遇到就没补ComboJack。iMessage不知道是不是个例，我这边是可用的

**Comment by iXeor** [comment]
FaceTime也测试过，是可以正常工作的。可能是进黑名单了
