### ISSUE TITLE
安装过程出现错误，这是什么原因呢

### ISSUE THREAD

**Issue by zyh530** [iXeor/Dell-Inspiron-7572-BigSur-OC#4]
![444c4d23469b6b2b2c0f1b468bb1edb](https://user-images.githubusercontent.com/50652658/121645542-e472db80-cac6-11eb-840a-a195a4590685.jpg)

**Comment by iXeor** [comment]
ACPI异常，应该是EFI配置和安装程序不太兼容。可以试试用早一些版本的Release安装

**Comment by zyh530** [comment]
是早一些的bigsur版本？

**Comment by zyh530** [comment]
![IMG_20210613_084117](https://user-images.githubusercontent.com/50652658/121792099-958e8880-cc23-11eb-85cf-70b634cae1c0.jpg)
还有这个错误，谢谢

**Comment by iXeor** [comment]
这个是NVMe断言失败，应该还是驱动伪装出了问题（比如使用了驱动不支持的固态硬盘或者其他的问题）或者系统镜像不完整造成的。然后之前说的是把EFI配置文件换成旧的试试。大概这个样子

**Comment by zyh530** [comment]
好的，谢谢

**Comment by zyh530** [comment]
还是一直有报错，各种问题，我原先的efi更新之后声卡失效了，关于声卡驱动你是咋么搞的，或者加个qq:1763255512?

**Comment by iXeor** [comment]
声卡驱动我也更新了，但是没有问题啊。耳机插口那个要补一个ComboJack
一直有报错可以先用黑果小兵的Clover EFI安装，之后再用我这个引导试试。

**Comment by Dionysen** [comment]
网卡“Intel Wi-Fi 6 AX200 160MHz”是笔记本上自带的吗，我的安装之后不能联网，请问是为什么呢

**Comment by iXeor** [comment]
AX200是我后换的，原装的是博通的网卡。

**Comment by iXeor** [comment]
然后我把博通那个驱动屏蔽了（原装网卡的也没法用，得换）

**Comment by Dionysen** [comment]
那么换的网卡能完美装到机器里面吗

**Comment by Dionysen** [comment]
或者能给个这片网卡的购买链接吗

**Comment by iXeor** [comment]
AX200的话连接不稳定
链接......淘宝搜一下就可以
博通卡的驱动没删，但是启动附加指令要改
博通的那个查DW1560

**Comment by Dionysen** [comment]
谢谢啦
